services:
    laravel.test:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
                MYSQL_CLIENT: mariadb-client
        image: sail-8.3/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - mariadb
            - mongodb
            - redis
            - scylla
    mariadb:
        image: "mariadb:11"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "sail-mariadb:/var/lib/mysql"
            - "./vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - "--connect"
                - "--innodb_initialized"
            retries: 3
            timeout: 5s
    mongodb:
        image: "mongodb/mongodb-atlas-local:latest"
        environment:
            - "MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-}"
            - "MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-}"
        volumes:
            - "sail-mongodb:/data/db"
        ports:
            - "${FORWARD_MONGODB_PORT:-27017}:27017"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mongosh
                - "mongodb://localhost:27017/admin"
                - "--eval=db.runCommand({ping:1})"
            retries: 3
            timeout: 5s
    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    audit-microservice:
        build:
            context: ./audit-ms
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            SCYLLADB_HOST: scylla
            SCYLLADB_PORT: 9042
        depends_on:
            - scylla
        networks:
            - sail
    scylla:
        image: scylladb/scylla:latest
        ports:
            - "9042:9042"
        volumes:
            - ./docker/scylladb/init.cql:/docker-entrypoint-initdb.d/init.cql
            - scylla-data:/var/lib/scylla
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
    sail-mongodb:
        driver: local
    sail-redis:
        driver: local
    scylla-data:
        driver: local
